### ISSUE TITLE
Testing Framework for quantum simulators

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qasm-testsuite#3]
## Context

---

## Tasks

- [x] Create a repository with a testing framework
- [ ] Tests should be automated (e.g. Pytest)
- [ ] Test edge cases with all available simulators

---

## Notes

Use QHana or Qunicorn for testing. Should be switchable via environment variable
